apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: static-websites
  name: jargonary-website
  labels:
    app: jargonary-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jargonary-website
  template:
    metadata:
      labels:
        app: jargonary-website
    spec:
      containers:
      - name: jargonary-website
        image: "ghcr.io/jargonary/jargonary.org:dockerize"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: static-websites
  name: jargonary-website
  labels:
    app: jargonary-website
spec:
  type: ClusterIP
  selector:
    app: jargonary-website
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: static-websites
  name: jargonary-website
  labels:
    app: jargonary-website
spec:
  ingressClassName: caddy
  rules:
  - host: jargonary.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jargonary-website
            port:
              number: 80
  - host: www.jargonary.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jargonary-website
            port:
              number: 80
